### ISSUE TITLE
Can’t find API key field

### ISSUE THREAD

**Issue by konorlevich** [gk646/CodeStats#1]
Plugin version: 1.4.0

<img width="1407" alt="Screenshot 2023-10-12 at 18 46 29" src="https://github.com/gk646/CodeStats/assets/15093064/ebf327f2-a2a8-4f4a-a39d-3f2978d5ad1c">

**Comment by gk646** [comment]
Hey, 
thanks for creating an issue. However i do not know what you are referring to. Why would there be an API key field and for what kind of functionality?
CodeStats does all its work on your local machine and just scans the files in the project directory and displays it in your IDE.
There is no external work or data being sent, hence no need for an API key.

**Comment by konorlevich** [comment]
<img width="435" alt="Screenshot 2023-10-13 at 07 45 04" src="https://github.com/gk646/CodeStats/assets/15093064/586b5639-0bd6-4ceb-b1be-7ea1574379cb">

I'm sorry, wrong plugin
It seems like JetBrains changed plugin search algorythm
