### ISSUE TITLE
Codeline counter -- modified in 2.0?

### ISSUE THREAD

**Issue by ewi2345** [gk646/CodeStats#10]
Greetings, 
After I installed 2.0, I saw an immediate drop in number of code lines (about 30%) ..  I have attached an image of this drop..
The ratio of Lines vs Lines CODE is 2 ... I don't think that only 50% of my lines is code .. the previous 70-75% sounded more realistic ..
So, was there a change in the way you could code lines (for Python)
Best
E
![Screenshot 2024-05-08 114404](https://github.com/gk646/CodeStats/assets/15355566/1fde62cb-9267-4581-aba5-ce67f798e188)

**Comment by ewi2345** [comment]
Honestly, I find the current results "unnatural" - according to my stat: only 50% of all lines are considered code. I don't think I use that many comments or empty lines ... it doesn't simply "feel" right.
Providing an option sounds really a good idea. 
What is a code line is an interesting question - IMHO: any line that is not empty and that is not in its entirety a comment line - that would be my expectation

**Comment by gk646** [comment]
Added a checkbox!

**Comment by ewi2345** [comment]
I have checked ur results with a quick code I wrote for my Python Code .. You have a bug in your counter .. I can't upload my source code here on this public website .. But I could sent u a pm with that code .. if you tell me how ..
Most extreme example .. there was one file with 1048 total lines, but only 91 lines of code -- and only 25 blank lines .. I analyzed that file and I got 699 code lines and 173 blank lines ..
This file was no exception ... from the 92 files:  for 36 files have a deviation in the number of code lines and 33 files with different blank line count - usually a significant difference in blank lines

**Comment by gk646** [comment]
Yes, with the new misc lines it wont add up to total lines count. 
This was just due to lazyness on my side as i didnt add misc lines as a table column.
But as i said all lines starting with an import and package statements will be excluded if you dont check the checkbox in the settings in update 2.0.1.
I did test it a bit and it worked fine in my tests
Also i didnt change too so i wouldnt expect a big bug.

**Comment by gk646** [comment]
Nevermind i found the bug.
Just check the standard python library with the new directory scan feature.
If the triple ending quote is in the same line its not closed.
So all lines are counted as documentation.
Will fix asap

**Comment by gk646** [comment]
![image](https://github.com/gk646/CodeStats/assets/116672956/3d8c1237-d680-4c68-8f88-15d82c872418)
For anyone whos interested.
These values do look better now than before.
Uploading new version now.
