### ISSUE TITLE
Obj and bin folders are not excluded

### ISSUE THREAD

**Issue by XiaofengdiZhu** [gk646/CodeStats#11]
![Snipaste_2024-11-07_12-43-13](https://github.com/user-attachments/assets/08ec9e09-79fb-48a2-a944-233ca5596d46)
By the way, I suggest that the "Excluded Directories" option can add regrex strings.

**Comment by gk646** [comment]
Thanks for the report.
I will add regex along with other fixes soon.

**Comment by gk646** [comment]
Coming tomorrow!

**Comment by gk646** [comment]
Submitted the update. Will be reviewed and available tomorrow!
Also the built in exclusion only works at the root: e.g. /obj
But now with regex you can exclude it anywhere!
