### ISSUE TITLE
add option to exclude .gradle directory

### ISSUE THREAD

**Issue by assylias** [gk646/CodeStats#2]
Great plugin!

I use gradle as a build tool and all projects contain a .gradle folder which itself contains java files that I would like to exclude. At the moment, I need to add an exclusion in each project.
Could you add  a "exclude .gradle folder" setting that would apply to all projects?
Or maybe allow to give a regex to exclude directories, e.g. ".*/.gradle(/.*)?"
Or "Exclude build tools directories (.gradle|target|gradle|build|dist)"?

**Comment by gk646** [comment]
Yes for sure I can add an exclude ".gradle" option. Its an oversight its not already there.
It will likely be added as you suggested, in the build tools option.
Thanks for submitting the issue!

**Comment by gk646** [comment]
The new update is submitted and should be live for in about 2 days! If the issue isnt fixed or something else comes up let me know!
