### ISSUE TITLE
Release v1.5.4 is not compatible with PyCharm 2023.3 and IntelliJ IDEA 2023.3

### ISSUE THREAD

**Issue by mo7ty** [gk646/CodeStats#6]
The latest release (v1.5.4) is not compatible with PyCharm 2023.3 and IntelliJ IDEA 2023.3.

**Comment by gk646** [comment]
Thank you for the report. Could you specify the issue further?
I did compatability checks for the plugin on the jetbrains website and they all showed full compatibility.
Further there are no methodes used that are marked for removal or marked as deprecated.

**Comment by gk646** [comment]
The problem was a fixed version number set in the plugin.xml file up until which it is compatible.
With this new version the static check against this version failed.
I removed setting this property now at all to avoid future issues.
