### ISSUE TITLE
CodeStats not supported in Jetbrain 2024.1

### ISSUE THREAD

**Issue by ewi2345** [gk646/CodeStats#8]
I need to report that CodeStats is not supported/available in Jetbrain 2024.1 (EAP)

**Comment by gk646** [comment]
Thank you for creating an issue.
Could you specify the exact issue? Does it not show up in the plugin marketplace? Or does it throw errors?

**Comment by gk646** [comment]
The dependency check is successful. I would guess this is an issue with the supported versions not properly updating for the plugins.
![grafik](https://github.com/gk646/CodeStats/assets/116672956/d8087a9c-a3c8-415b-a579-59fa141c94c8)
I can try uploading a new version and check if the new version is included.

**Comment by gk646** [comment]
Its probably related to this setting. I cannot change it sadly even tho i didnt specify it inside the plugin.xml as stated in their version number guide. (To indicate compatibility to all future versions) Are other addons working?
![grafik](https://github.com/gk646/CodeStats/assets/116672956/4b6bc4ef-7c99-4f9d-a314-5a6e32744650)

**Comment by ewi2345** [comment]
Yeah, there are a couple of plugins not working .. Initially among them was also Github Copilot ... but they fixed it.
![Screenshot 2024-01-27 045511](https://github.com/gk646/CodeStats/assets/15355566/9284398a-3b6c-4d25-bcd9-1b5e4b29087d)

**Comment by gk646** [comment]
Alright i should have the fix for it, by looking through the source code of the working plugins you showed here. You can add a line patchXML where you can also specify the empty field for untilBuild. Somehow this works over setting it inside the plugin.xml.
Will delete and reupload the version 1.5.6 with this fix.

**Comment by gk646** [comment]
Plugins now cant be deleted instantly anymore. I just uploaded the new version 1.5.7 thats version unlocked. 
![image](https://github.com/gk646/CodeStats/assets/116672956/5cad145d-1170-47a1-9ad4-46f2816aab95)
