### ISSUE TITLE
Language specific filtering - ignore Java/Kotlin imports + notes

### ISSUE THREAD

**Issue by murfel** [gk646/CodeStats#9]
It would be nice to filter out the "import ..." lines in Java/Kotlin and `#include <...>` / `#include "..."` in C++. Those constitute another ~5% of source code in medium-sized projects. It could be done with a regex.

On a side note - it would be clearer if the plugin description on JetBrains plugins website would specify that you only support C/C++/Java-style comments and docstrings and Python/Bash-style comments. (It looks like [parseFile](https://github.com/gk646/CodeStats/blob/main/src/main/java/com/gk646/codestats/stats/Parser.java#L377) doesn't fully cover [Python docstrings](https://peps.python.org/pep-0257/#what-is-a-docstring) in `""" triple quotation marks """`.)

There is a whole [zoo of comment styles](https://www.gavilan.edu/csis/languages/comments.html#_Toc53710125). The examples are a bit historical, but even modern languages use those comment styles, e.g. Haskell uses `--`, OCaml uses `( * comment * )`, etc.

Also, if you're interested, I'd love to offer you a code review, feel free to DM me on twitter.com/murf3l.

Anyways, thank you for your plugin! It saved some time for me to do it manually :) I might even have a use case which would benefit ~100 people per year - I could ask students to provide the statistics alongside the final project submission, for a first glimpse into the effort a student made.

**Comment by gk646** [comment]
Hello,
thanks for the issue and the nice comments.
Yes thats correct about the comments, i can more clearly specify that.
I also like the idea about removing the import statements aswell.
If i find the time ill look into it and add it along with other requested features. 
Thanks for using CodeStats and even sharing it!
